
[general]
live_config_reload = true

# [shell]
# program = "/usr/bin/fish"

[window]
padding = { x = 15, y = 15 }
blur = true
opacity = 0.80

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[keyboard]
bindings = [
{ key = "l", mods = "Alt", action = "ReceiveChar" },
]
