base-url: 'https://ntfy.treywilkinson.com'
listen-http: ":80"
listen-https: ":443"
key-file: "/etc/letsencrypt/live/ntfy.treywilkinson.com/privkey.pem"
cert-file: "/etc/letsencrypt/live/ntfy.treywilkinson.com/fullchain.pem"
cache-file: "/var/cache/ntfy/cache.db"
behind-proxy: false
