services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy-net
      - nextcloud-net

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./ntfy/cache:/var/cache/ntfy
      - ./ntfy/config:/etc/ntfy # For server.yml configuration
    command:
      - serve
    networks:
      - proxy-net

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - ntfy
  #   restart: unless-stopped
  #   networks:
  #     - proxy-net

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./vw-data:/data
    # environment:
    # Customize environment variables as needed
    # - WEBSOCKET_ENABLED=true
    # - SIGNUPS_ALLOWED=false
    # - ADMIN_TOKEN=your_admin_token_here
    networks:
      - proxy-net

  mariadb:
    image: linuxserver/mariadb:latest
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=super-secret-root-password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=super-secret-db-password
      - TZ=America/New_York
    volumes:
      - /mnt/drive/nextcloud/mysql:/var/lib/mysql # ON SSD
    restart: unless-stopped
    networks:
      - nextcloud-net

  redis:
    image: redis:6-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - /mnt/drive/nextcloud/redis:/data
    networks:
      - nextcloud-net

  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    depends_on:
      - mariadb
      - redis
    volumes:
      - /mnt/drive/nextcloud/html:/config # app config
      - /mnt/drive/nextcloud/data:/data # nextcloud user files (VERY important)
    restart: unless-stopped
    networks:
      - nextcloud-net

  # zortex:
  #   build: ./zortex
  #   container_name: zortex
  #   restart: unless-stopped
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./zortex/data
  #   environment:
  #     # Core settings
  #     - PORT=5000
  #     - DB_PATH=/data/zortex.db

  #     # Authentication - CHANGE THESE!
  #     - API_KEY=${ZORTEX_API_KEY:-your-secure-api-key-here}
  #     - BASIC_AUTH_USER=${ZORTEX_USER:-admin}
  #     - BASIC_AUTH_PASS=${ZORTEX_PASS:-change-me-please}
  #     - SECRET_KEY=${ZORTEX_SECRET:-generate-random-key}

  #     # Notification settings
  #     - NTFY_URL=${NTFY_URL:-http://ntfy:8080}
  #     - NTFY_TOPIC=${NTFY_TOPIC:-zortex}
  #     - CHECK_INTERVAL=60

  #     # Email settings (optional)
  #     - EMAIL_ENABLED=${EMAIL_ENABLED:-false}
  #     - SES_REGION=${SES_REGION:-us-east-1}
  #     - FROM_EMAIL=${FROM_EMAIL:-digest@example.com}
  #     - TO_EMAIL=${TO_EMAIL:-user@example.com}

  #   networks:
  #     - proxy-net

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy-net:
    driver: bridge
  nextcloud-net:
    driver: bridge
