#!/bin/sh -e

SCRIPT_DIR=$(git rev-parse --show-toplevel)
SYSTEM_TYPE="aarch64-darwin-wgu"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"
echo $SCRIPT_DIR

export NIXPKGS_ALLOW_UNFREE=1
export IMPURITY_PATH="$SCRIPT_DIR"

# Build and Switch
nix --extra-experimental-features 'nix-command flakes' build --impure .#$FLAKE_SYSTEM --show-trace
sudo --preserve-env=NIXPKGS_ALLOW_UNFREE,IMPURITY_PATH ./result/sw/bin/darwin-rebuild switch --impure --flake .#${SYSTEM_TYPE}
unlink ./result

# Clear the environment for wgu
"$SCRIPT_DIR/apps/wgu-env" clear
