#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="aarch64-darwin-impure"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1
export IMPURITY_PATH=$(git rev-parse --show-toplevel)

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build --impure .#$FLAKE_SYSTEM --show-trace $@

echo "${YELLOW}Switching to new generation...${NC}"
sudo --preserve-env=NIXPKGS_ALLOW_UNFREE,IMPURITY_PATH ./result/sw/bin/darwin-rebuild switch --impure --flake .#${SYSTEM_TYPE} $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
