["ghc/ghc"]
tags = []
aliases = []
author = "ghc"
repository = "ghc"

["redox-os/redox"]
tags = []
aliases = []
author = "redox-os"
repository = "redox"

["nodejs/node"]
tags = []
aliases = []
author = "nodejs"
repository = "node"

["three.js/.gitattributes"]
tags = []
aliases = []
author = "three.js"
repository = ".gitattributes"

["three.js/icon.png"]
tags = []
aliases = []
author = "three.js"
repository = "icon.png"

["three.js/.gitignore"]
tags = []
aliases = []
author = "three.js"
repository = ".gitignore"

["three.js/LICENSE"]
tags = []
aliases = []
author = "three.js"
repository = "LICENSE"

["three.js/.github"]
tags = []
aliases = []
author = "three.js"
repository = ".github"

["three.js/package-lock.json"]
tags = []
aliases = []
author = "three.js"
repository = "package-lock.json"

["three.js/.git"]
tags = []
aliases = []
author = "three.js"
repository = ".git"

["three.js/files"]
tags = []
aliases = []
author = "three.js"
repository = "files"

["three.js/src"]
tags = []
aliases = []
author = "three.js"
repository = "src"

["three.js/editor"]
tags = []
aliases = []
author = "three.js"
repository = "editor"

["three.js/utils"]
tags = []
aliases = []
author = "three.js"
repository = "utils"

["three.js/build"]
tags = []
aliases = []
author = "three.js"
repository = "build"

["three.js/test"]
tags = []
aliases = []
author = "three.js"
repository = "test"

["three.js/package.json"]
tags = []
aliases = []
author = "three.js"
repository = "package.json"

["three.js/examples"]
tags = []
aliases = []
author = "three.js"
repository = "examples"

["three.js/.editorconfig"]
tags = []
aliases = []
author = "three.js"
repository = ".editorconfig"

["three.js/README.md"]
tags = []
aliases = []
author = "three.js"
repository = "README.md"

["three.js/docs"]
tags = []
aliases = []
author = "three.js"
repository = "docs"

["thomas10-10/foo-Wallpaper-Feh-Gif"]
tags = []
aliases = []
author = "thomas10-10"
repository = "foo-Wallpaper-Feh-Gif"

["BurntSushi/ripgrep"]
tags = []
aliases = []
author = "BurntSushi"
repository = "ripgrep"

["strapi/strapi"]
tags = []
aliases = []
author = "strapi"
repository = "strapi"

["strapi/strapi-examples"]
tags = []
aliases = []
author = "strapi"
repository = "strapi-examples"

["alacritty/alacritty"]
tags = []
aliases = []
author = "alacritty"
repository = "alacritty"

["numpy/numpy"]
tags = []
aliases = []
author = "numpy"
repository = "numpy"

["iamkun/dayjs"]
tags = []
aliases = []
author = "iamkun"
repository = "dayjs"

["torvalds/linux"]
tags = []
aliases = []
author = "torvalds"
repository = "linux"

["xmonad/xmonad"]
tags = []
aliases = []
author = "xmonad"
repository = "xmonad"

["tryone144/compton"]
tags = []
aliases = []
author = "tryone144"
repository = "compton"

["jonaburg/picom"]
tags = []
aliases = []
author = "jonaburg"
repository = "picom"

["lodash/lodash"]
tags = []
aliases = []
author = "lodash"
repository = "lodash"

["pytorch/pytorch"]
tags = []
aliases = []
author = "pytorch"
repository = "pytorch"

["t-wilkinson/scripts"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "scripts"

["t-wilkinson/vim-zettelkasten"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "vim-zettelkasten"

["t-wilkinson/vim-mdnav"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "vim-mdnav"

["t-wilkinson/npm-rxjs-redux-store"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "npm-rxjs-redux-store"

["t-wilkinson/projects"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "projects"

["t-wilkinson/dotfiles"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "dotfiles"

["t-wilkinson/infinite-closet"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "infinite-closet"

["t-wilkinson/lsystem"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "lsystem"

["t-wilkinson/N.E.A.T."]
tags = []
aliases = []
author = "t-wilkinson"
repository = "N.E.A.T."

["t-wilkinson/sysadmin"]
tags = []
aliases = []
author = "t-wilkinson"
repository = "sysadmin"

["golang/go"]
tags = []
aliases = []
author = "golang"
repository = "go"

["Kethku/neovide"]
tags = []
aliases = []
author = "Kethku"
repository = "neovide"

["ethanyanjiali/deep-vision"]
tags = []
aliases = []
author = "ethanyanjiali"
repository = "deep-vision"

["saltstack/salt"]
tags = []
aliases = []
author = "saltstack"
repository = "salt"

["facebook/react"]
tags = []
aliases = []
author = "facebook"
repository = "react"

["openbsd/src"]
tags = []
aliases = []
author = "openbsd"
repository = "src"

["suckless/dmenu"]
tags = []
aliases = []
author = "suckless"
repository = "dmenu"

["suckless/st"]
tags = []
aliases = []
author = "suckless"
repository = "st"

["ReactiveX/rxjs"]
tags = []
aliases = []
author = "ReactiveX"
repository = "rxjs"

["Stichting-MINIX-Research-Foundation/minix"]
tags = []
aliases = []
author = "Stichting-MINIX-Research-Foundation"
repository = "minix"

["junegunn/fzf"]
tags = []
aliases = []
author = "junegunn"
repository = "fzf"

["neovim/neovim"]
tags = []
aliases = []
author = "neovim"
repository = "neovim"

["python/cpython"]
tags = []
aliases = []
author = "python"
repository = "cpython"

["d3/d3"]
tags = []
aliases = []
author = "d3"
repository = "d3"

["rust-lang/rust"]
tags = []
aliases = []
author = "rust-lang"
repository = "rust"

["GNU/gcc"]
tags = []
aliases = []
author = "GNU"
repository = "gcc"

["GNU/coreutils"]
tags = []
aliases = []
author = "GNU"
repository = "coreutils"

["GNU/gnulib"]
tags = []
aliases = []
author = "GNU"
repository = "gnulib"

["qutebrowser/qutebrowser"]
tags = []
aliases = []
author = "qutebrowser"
repository = "qutebrowser"

["archlinux/archinstall"]
tags = []
aliases = []
author = "archlinux"
repository = "archinstall"
