# EXAMPLES: https://github.com/starship/starship/discussions/1252
command_timeout = 100

# # Don't print a new line at the start of the prompt
# add_newline = false
# # Pipes ╰─ ╭─
# # Powerline symbols                                     
# # Wedges 🭧🭒 🭣🭧🭓
# # Random noise 🬖🬥🬔🬗
# 
# # format = """
# # $cmd_duration$username$hostname $directory $git_branch
# # $character
# # """
# format = """
# $cmd_duration$directory $git_branch
# $character
# """
# 
# # Replace the "❯" symbol in the prompt with "➜"
# [character]                            # The name of the module we are configuring is "character"
# success_symbol = "[• ](bold fg:blue) "
# error_symbol = "[• 󰅙](bold fg:red) "
# 
# # Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true
# 
# [git_branch]
# style = "bg: green"
# symbol = "󰘬"
# truncation_length = 20
# truncation_symbol = ""
# format = "• [](bold fg:green)[$symbol $branch(:$remote_branch)](fg:black bg:green)[ ](bold fg:green)"
# 
# [git_commit]
# commit_hash_length = 4
# tag_symbol = " "
# 
# [git_state]
# format = '[\($state( $progress_current of $progress_total)\)]($style) '
# cherry_pick = "[🍒 PICKING](bold red)"
# 
# [git_status]
# conflicted = " 🏳 "
# ahead = " 🏎💨 "
# behind = " 😰 "
# diverged = " 😵 "
# untracked = " 🤷 ‍"
# stashed = " 📦 "
# modified = " 📝 "
# staged = '[++\($count\)](blue)'
# renamed = " ✍️ "
# deleted = " 🗑 "
# 
# [hostname]
# ssh_only = false
# format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan )"
# trim_at = ".companyname.com"
# disabled = false
# 
# [line_break]
# disabled = false
# 
# [memory_usage]
# disabled = true
# threshold = -1
# symbol = " "
# style = "bold dimmed blue"
# 
# [time]
# disabled = true
# format = '🕙[\[ $time \]]($style) '
# time_format = "%T"
# 
# [username]
# style_user = "bold bg:cyan fg:black"
# style_root = "red bold"
# format = "[](bold fg:cyan)[$user]($style)"
# disabled = false
# show_always = true
# 
# [directory]
# home_symbol = "  "
# read_only = "  "
# style = "bg:blue fg:black"
# truncation_length = 30
# truncation_symbol = "••/"
# format = '[](bold fg:blue)[$path ]($style)[](bold fg:blue)'
# 
# 
# [directory.substitutions]
# "Desktop" = "  "
# "Documents" = "  "
# "Downloads" = "  "
# "Music" = " 󰎈 "
# "Pictures" = "  "
# "Videos" = "  "
# "hyprland" = "  "
# "GitHub" = "  "
# 
# [cmd_duration]
# min_time = 0
# format = '[](bold fg:yellow)[ $duration](bold bg:yellow fg:black)[](bold fg:yellow) •• '
# 


# PROMPT: pastel
# format = """
# [](#9A348E)\
# $os\
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [](fg:#FCA17D bg:#86BBD8)\
# $c\
# $elixir\
# $elm\
# $golang\
# $gradle\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# $scala\
# [](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [](fg:#06969A bg:#33658A)\
# $time\
# [ ](fg:#33658A)\
# """
# 
# # Disable the blank line at the start of the prompt
# # add_newline = false
# 
# # You can also replace your username with a neat symbol like   or disable this
# # and use the os module below
# [username]
# show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
# format = '[$user ]($style)'
# disabled = false
# 
# # An alternative to the username module which displays a symbol that
# # represents the current operating system
# [os]
# style = "bg:#9A348E"
# disabled = true # Disabled by default
# 
# [directory]
# style = "bg:#DA627D"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
# 
# # Here is how you can shorten some long paths by text replacement
# # similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# # Keep in mind that the order matters. For example:
# # "Important Documents" = " 󰈙 "
# # will not be replaced, because "Documents" was already substituted before.
# # So either put "Important Documents" before "Documents" or use the substituted version:
# # "Important 󰈙 " = " 󰈙 "
# 
# [c]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [docker_context]
# symbol = " "
# style = "bg:#06969A"
# format = '[ $symbol $context ]($style)'
# 
# [elixir]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [elm]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [git_branch]
# symbol = ""
# style = "bg:#FCA17D"
# format = '[ $symbol $branch ]($style)'
# 
# [git_status]
# style = "bg:#FCA17D"
# format = '[$all_status$ahead_behind ]($style)'
# 
# [golang]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [gradle]
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [haskell]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [java]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [julia]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [nodejs]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [nim]
# symbol = "󰆥 "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [rust]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [scala]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[ $symbol ($version) ]($style)'
# 
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
# format = '[ ♥ $time ]($style)'
# 
# 
# [aws]
# symbol = "  "
# 
# [buf]
# symbol = " "
# 
# [conda]
# symbol = " "
# 
# [crystal]
# symbol = " "
# 
# [dart]
# symbol = " "
# 
# [fennel]
# symbol = " "
# 
# [fossil_branch]
# symbol = " "
# 
# [guix_shell]
# symbol = " "
# 
# [haxe]
# symbol = " "
# 
# [hg_branch]
# symbol = " "
# 
# [hostname]
# ssh_symbol = " "
# 
# [kotlin]
# symbol = " "
# 
# [lua]
# symbol = " "
# 
# [memory_usage]
# symbol = "󰍛 "
# 
# [meson]
# symbol = "󰔷 "
# 
# [nix_shell]
# symbol = " "
# 
# [ocaml]
# symbol = " "
# 
# [os.symbols]
# Alpaquita = " "
# Alpine = " "
# AlmaLinux = " "
# Amazon = " "
# Android = " "
# Arch = " "
# Artix = " "
# CentOS = " "
# Debian = " "
# DragonFly = " "
# Emscripten = " "
# EndeavourOS = " "
# Fedora = " "
# FreeBSD = " "
# Garuda = "󰛓 "
# Gentoo = " "
# HardenedBSD = "󰞌 "
# Illumos = "󰈸 "
# Kali = " "
# Linux = " "
# Mabox = " "
# Macos = " "
# Manjaro = " "
# Mariner = " "
# MidnightBSD = " "
# Mint = " "
# NetBSD = " "
# NixOS = " "
# OpenBSD = "󰈺 "
# openSUSE = " "
# OracleLinux = "󰌷 "
# Pop = " "
# Raspbian = " "
# Redhat = " "
# RedHatEnterprise = " "
# RockyLinux = " "
# Redox = "󰀘 "
# Solus = "󰠳 "
# SUSE = " "
# Ubuntu = " "
# Unknown = " "
# Void = " "
# Windows = "󰍲 "
# 
# [package]
# symbol = "󰏗 "
# 
# [perl]
# symbol = " "
# 
# [php]
# symbol = " "
# 
# [pijul_channel]
# symbol = " "
# 
# [python]
# symbol = " "
# 
# [rlang]
# symbol = "󰟔 "
# 
# [ruby]
# symbol = " "
# 
# [swift]
# symbol = " "
# 
# [zig]
# symbol = " "


# format = """\
# [](bg:#030B16 fg:#7DF9AA)\
# [󰀵 ](bg:#7DF9AA fg:#090c0c)\
# [](fg:#7DF9AA bg:#1C3A5E)\
# $time\
# [](fg:#1C3A5E bg:#3B76F0)\
# $directory\
# [](fg:#3B76F0 bg:#FCF392)\
# $git_branch\
# $git_status\
# $git_metrics\
# [](fg:#FCF392 bg:#030B16)\
# $character\
# """
# 
# [directory]
# format = "[ ﱮ $path ]($style)"
# style = "fg:#E4E4E4 bg:#3B76F0"
# 
# [git_branch]
# format = '[ $symbol$branch(:$remote_branch) ]($style)'
# symbol = "  "
# style = "fg:#1C3A5E bg:#FCF392"
# 
# [git_status]
# format = '[$all_status]($style)'
# style = "fg:#1C3A5E bg:#FCF392"
# 
# [git_metrics]
# format = "([+$added]($added_style))[]($added_style)"
# added_style = "fg:#1C3A5E bg:#FCF392"
# deleted_style = "fg:bright-red bg:235"
# disabled = false
# 
# [hg_branch]
# format = "[ $symbol$branch ]($style)"
# symbol = " "
# 
# [cmd_duration]
# format = "[  $duration ]($style)"
# style = "fg:bright-white bg:18"
# 
# [character]
# success_symbol = '[ ➜](bold green) '
# error_symbol = '[ ✗](#E84D44) '
# 
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
# format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'


# PROMPT: pure
# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $cmd_duration\
# $line_break\
# $python\
# $character"""
# 
# [directory]
# style = "blue"
# 
# [character]
# success_symbol = "[❯](purple)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"
# 
# [git_branch]
# format = "[$branch]($style)"
# style = "bright-black"
# 
# [git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
# style = "cyan"
# conflicted = "​"
# untracked = "​"
# modified = "​"
# staged = "​"
# renamed = "​"
# deleted = "​"
# stashed = "≡"
# 
# [git_state]
# format = '\([$state( $progress_current/$progress_total)]($style)\) '
# style = "bright-black"
# 
# [cmd_duration]
# format = "[$duration]($style) "
# style = "yellow"
# 
# [python]
# format = "[$virtualenv]($style) "
# style = "bright-black"


# Custom user
# format = """
# $username\
# $shlvl\
# $kubernetes\
# ${custom.dir}\
# ${custom.home_dir}\
# $directory\
# ${custom.git_host}\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $hg_branch\
# $docker_context\
# $package\
# $cmake\
# $dart\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $kotlin\
# $nim\
# $nodejs\
# $ocaml\
# $perl\
# $php\
# $purescript\
# $python\
# $ruby\
# $rust\
# $swift\
# $terraform\
# $vagrant\
# $zig\
# $nix_shell\
# $conda\
# $aws\
# $gcloud\
# $openstack\
# $env_var\
# $crystal\
# $custom\
# $cmd_duration\
# $lua\
# $line_break\
# $jobs\
# $status\
# $character"""
# 
# scan_timeout = 10
# 
# add_newline = false
# 
# [battery]
# disabled = true
# 
# [character]
# success_symbol = "[](bright-red)[](bright-blue)[](bright-cyan)"
# error_symbol = "[](red)"
# 
# [directory]
# truncation_length = 1
# format = "[ $path ]($style)[$read_only]($read_only_style) "
# style = "fg:white bg:black bold"
# read_only = "  "
# read_only_style = "fg:black bg:red"
# 
# [git_branch]
# format = ":[$symbol$branch]($style) "
# 
# [git_status]
# conflicted = "[<](white)=[$count](bright-white bold)[>](white)"
# ahead = "[<](white)⇡[$count](bright-white bold)[>](white)"
# behind = "[<](white)⇣[$count](bright-white bold)[>](white)"
# diverged = "[<](white)⇕⇡[$ahead_count](bright-white bold)⇣[$behind_count](bright-white)[>](white)"
# untracked = "[<](white)?[$count](bright-white bold)[>](white)"
# stashed = "[<](white)$[$count](bright-white bold)[>](white)"
# modified = "[<](white)![$count](bright-white bold)[>](white)"
# staged = "[<](white)+[$count](bright-white bold)[>](white)"
# renamed = "[<](white)»[$count](bright-white bold)[>](white)"
# deleted = "[<](white)✗[$count](bright-white bold)[>](white)"
# 
# [custom.home_dir]
# command = "echo  "
# when = '[ "$PWD" == "$HOME" ]'
# shell = ["bash", "--norc", "--noprofile"]
# style = "fg:bright-white bg:bright-black"
# format = "[ $output ]($style)"
# 
# [custom.dir]
# command = "echo  "
# when = '[ "$PWD" != "$HOME" ]'
# shell = ["bash", "--norc", "--noprofile"]
# style = "fg:blue bg:bright-black"
# format = "[ $output ]($style)"
# 
# [custom.git_host]
# command = 'getgithost'
# when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
# shell = ["bash", "--norc", "--noprofile"]
# style = "bright-yellow bold"
# format = "at [$output]($style)"
# 
# [hostname]
# disabled = true


# PROMPT: nerd-font
[aws]
symbol = "  "
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

# [directory]
# read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "


[directory]
truncate_to_repo = true
truncation_length = 30
truncation_symbol = "…/"
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold"
# style = "fg:white bg:black bold"
read_only = "  "
# read_only = " 󰌾"
# read_only = "  "
# read_only_style = "fg:black bg:red"
home_symbol = "  "

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"hyprland" = "  "
"GitHub" = "  "
"dev" = "  "

format = """
$username\
$shlvl\
$kubernetes\
${custom.dir}\
${custom.home_dir}\
$directory\
${custom.git_host}\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$lua\
$line_break\
$jobs\
$status\
$character"""
