#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

FLAKE_TARGET="x86_64-linux-impure"

export NIXPKGS_ALLOW_UNFREE=1
export IMPURITY_PATH=$(pwd)

echo "${YELLOW}Starting build...${NC}"
# nix --extra-experimental-features 'nix-command flakes' build --impure .#$FLAKE_TARGET --show-trace $@
nixos-rebuild build --impure --flake .#$FLAKE_TARGET "$@"

echo "${YELLOW}Switching to new generation...${NC}"
/run/current-system/sw/bin/nixos-rebuild switch --impure --flake .#$FLAKE_TARGET "$@"

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
