#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="x86_64-linux-impure"
FLAKE_SYSTEM="nixosConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1
export IMPURITY_PATH=$(git rev-parse --show-toplevel)

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build --impure .#$FLAKE_SYSTEM --show-trace $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Build complete!${NC}"
