return {
  {
    "imsnif/kdl.vim",
  },

  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "angular-language-server",
        "bash-language-server",
        "clangd",
        "cmakelang",
        "cmakelint",
        "codelldb",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "gofumpt",
        "goimports",
        "gopls",
        "hadolint",
        "jdtls",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint-cli2",
        "marksman",
        "neocmakelsp",
        "prettier",
        "pyright",
        "ruff",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
        "terraform-ls",
        "tflint",
        "vtsls",
        "vue-language-server",
        "yaml-language-server",
      },
    },
  },

  -- {
  --   "williamboman/mason.nvim",
  --   opts = function(_, opts)
  --     vim.list_extend(opts.ensure_installed, {
  --       "pyright",
  --       "clangd",
  --       -- "stylua",
  --       -- "selene",
  --       -- "luacheck",
  --       -- "shellcheck",
  --       -- "shfmt",
  --       -- "tailwindcss-language-server",
  --       -- "typescript-language-server",
  --       -- "css-lsp",
  --     })
  --   end,
  -- },

  { "nvim-treesitter/nvim-treesitter-textobjects" },

  { "Saghen/blink.cmp" },

  {
    "nvim-treesitter/nvim-treesitter",
    enabled = true,
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "css",
        "diff",
        "gitignore",
        "go",
        "html",
        "http",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "ninja",
        "php",
        "printf",
        "python",
        "r",
        "regex",
        "rst",
        "rust",
        "sql",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "xml",
        "yaml",
      },
    },
  },
}
